### PR TITLE
Conversion of graph vignette to graph.Rmd file to replace graph.Rnw file

### PR DESCRIPTION
**Pull request by alatiku**
@Bioconductor/sweave2rmd please review my work. I created the RMarkdown file for the graph vignette.
Attached are the HTML [graph.zip](https://github.com/Bioconductor/graph/files/10941363/graph.zip) and the original PDF [graph.pdf](https://github.com/Bioconductor/graph/files/10941305/graph.pdf)

### CODE REVIEW

**Comment by jwokaty** [comment]
Hi @sirjoka,

I'm going to start your review. I'll give you a little feedback at a time (rather than all at once), so I can keep everyone moving. I'll be reviewing your based on the following checklist:

- [ ] the `.Rmd` file knits to `HTML`
- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [x] the `.Rnw` file has been removed
- [x] in the `DESCRIPTION`, `BiocStyle` and `knitr` are listed in `Suggests`
- [x] in the `DESCRIPITON`, the line `VignetteBuilder: knitr` exists
- [ ] any added lines use the same spacing and indents as the existing
  document
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the `DESCRIPTION` file; refer to the contribution guide for acceptable
  formats
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the vignette's YAML; refer to the contribution guide for acceptable formats
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, check that the
  `Authors@R` vector includes the maintainer as specified with `role='cre'`.
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, the `Maintainer` line
  is completely removed.
- [ ] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [ ] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [ ] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`

**Comment by jwokaty** [comment]
I noticed looking at your PR, that you want to merge from `sirjoka:devel` to `Bioconductor:devel`. Typically, we use [feature branch workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow), where we create new branch based on our canonical branch, 'devel', which has gone through testing, it's what our users use, etc., so that we isolate new features in a separate branch rather than directly making edits to the `devel` branch. After reading about the workflow, I recommend reading our [Contribute document](https://bioconductor.github.io/sweave2rmd/articles/contribute.html#create-the-r-markdown--rmd-vignette-and-remove-the-sweave-vignette--rnw) .

**Comment by jwokaty** [comment]
After looking at your commits, it looks like you have 2 similar commits, but I can't tell the difference between them without more investigation.

I think at this point, I want to ask you if you could try creating a feature branch with a commit to remove graph.Rnw and another commit to add graph.Rmd then do another PR. I would be careful as I see your devel branch on your forked repo is already updated with this code. I know you may not be familiar with branching and working with remote repositories, so let me give you 2 options:

Option 1: Deleting your repo and clone
1. Save your graph.Rmd outside your repo temporarily. 
2. Delete your clone on your machine
3. Delete your forked repo on Github
4. Fork github.com/Bioconductor/graph again
5. Clone github.com/sirjoka/graph again

Option 2: Branching
1. Save your graph.Rmd outside your repo temporarily
2. Rename your devel branch. We need to rename to avoid problems.
    `git branch -m devel olddevel`
4. Define an upstream remote. Remotes are repos not on your local computer; you have one already named 'origin', which points to your forked repo on github.
    `git remote -v # look at your remotes, you should see just origin`
    `git remote add upstream git@github.com:Bioconductor/graph`
    `git remote -v # Now you should have a remote named upstream pointing to the original repository you forked`
5. Fetch upstream to get the HEAD of upstream (this points to where the repo is in its history). You'll see it gets lots of branches.
    `git fetch upstream`
6. Switch to the devel branch
    `git switch devel # now we have a clean devel branch`

Once you've done the above, you can 
1. Follow the steps on the contribution document to create a new branch
2. Copy your graph.Rmd back into your new repo
3. Commit your graph.Rmd
4. Remove graph.Rnw and commit
5. Make your PR
 
 Please leave this PR open until your new PR is ready so you can ask questions here. If you'd like to do this together, you can ask me on slack and I will try to meet with you if I have time. I'm generally available 9AM-5PM ET on the weekdays.

**Comment by alatiku** [comment]
Hi okay. Thank you very much, i appreciate the guidance. But if I delete the forked repo, wouldn't it delete this PR also?

**Comment by jwokaty** [comment]
No, it should still be here :)

**Comment by alatiku** [comment]
> No, it should still be here :)

Alright. Thank you, I will work on your guide now to delete, fork and clone the repo then proceed.

**Pull request closed without merging**
