### PR TITLE
Convert MultiGraphClass to Rmd

### PR DESCRIPTION
**Pull request by Chisomgold**
Hi @jwokaty 

I just made the sweave to Rmd conversion for MultiGraphClass as part of the Sweave2Rmd project. I deleted the Rnw file and added Rmd.

Attached are the files for comparison: [MultiGraphClass PDF format](https://bioconductor.org/packages/devel/bioc/vignettes/graph/inst/doc/MultiGraphClass.pdf) and [MultiGraphClass HTML file](https://github.com/Bioconductor/graph/files/9838551/MultiGraphClass.zip)

### CODE REVIEW

**Comment by jwokaty** [comment]
Hi @Chisomgold I see that there are also commits for GraphClass, which is in a separate PR. Generally this happens when you `git switch` and create a new branch based on the branch you used for working on GraphClass. We generally always want to `git switch` back to the master branch then `git switch -c new-branch-name` on the master branch.

I would recommend the following
```
# Make sure you're on the MultiGraphClass-Rmd
git status
# Undo your last commit
git reset HEAD~
# Switch to the master branch
git switch master
# Delete the old branch
git branch -D MultiGraphClass-Rmd
# Create a new branch based on master
git switch -c MultiGraphClass-rmd
# Commit your changes (generally I suggest adding the Rmd and removing the Rnw in separate commits)
git add MultiGraphClass.Rmd
git commit -m 'Add MultiGraphClass.Rmd'
git rm MultiGraphClass.Rnw
git commit -m 'Remove MultiGraphClass.Rnw'
# Force push your change
git push -f origin MultiGraphClass-Rmd
```

I know this is a lot, but if you'd feel more comfortable walking through it together, slack me when you're online and we can do it in a slack huddle.

**Comment by jwokaty** [comment]
Yes, if the branch has a different name then open a new pull request and close this one.

**Comment by Chisomgold** [comment]
Actually, it's the same name and now there are two branches with that name. How do I fix that?

**Comment by jwokaty** [comment]
So we want the branch that only has the commits for MultiGraphClass. If you followed my instructions above, your new branch must be `MultiGraphClass-rmd` so you'll want to push that and make a new pull request. I am going to close this one.

**Comment by jwokaty** [comment]
While I was reviewing your other pull request, I saw the two branches you have. It looks like you want to push the one named `MultiClassGraph-Rmd`. The names are different. You can always see what branches you have with `git branch -v`.

**Pull request closed without merging**
